export const ADD_SELECTOR = "ADD_SELECTOR";
export const REMOVE_SELECTOR = "REMOVE_SELECTOR";
export const SET_SELECTOR_NAME = "SET_SELECTOR_NAME";
export const SET_SELECTOR_SELECTOR = "SET_SELECTOR_SELECTOR";
export const SET_SELECTOR_SHOW_PREVIEW = "SET_SELECTOR_SHOW_PREVIEW";
export const SET_SELECTOR_BROWSER_WIDTH = "SET_SELECTOR_BROWSER_WIDTH";
